package pl.marcinlipinski.matchbettingapp.controller;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.scene.text.Text;
import net.rgielen.fxweaver.core.FxControllerAndView;
import net.rgielen.fxweaver.core.FxmlView;
import org.springframework.stereotype.Component;

@Component
@FxmlView
public class MainCoverControler {
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @FXML
    private final FxControllerAndView<SummaryPaneController, AnchorPane> summaryPane;

    public MainCoverControler(FxControllerAndView<SummaryPaneController, AnchorPane> summaryPane) {
        this.summaryPane = summaryPane;
    }

    @FXML
    public Button openDialogButton;
    public Button AccountResetButton;
    public Text AccountBalanceLabel;


    @FXML
    public void initialize() {
        //openDialogButton.setOnAction(
        //        actionEvent -> someDialog.getController().show()
        //);
    }
}
